services:
  graphql:
    build: .
    container_name: nextmavens-graphql
    environment:
      - PORT=4004
      - DATABASE_URL=postgresql://nextmavens:Elishiba@95@nextmavens-db-m4sxnf:5432/nextmavens
      - JWT_SECRET=nextmavens-auth-secret-key-2024-production-secure
    ports:
      - "4004:4004"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
