services:
  realtime:
    build: .
    # container_name: nextmavens-realtime
    env_file:
      - .env
    environment:
      - PORT=${PORT:-4003}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "4003:4003"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
